# Generated by Django 2.0.7 on 2018-07-23 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('telephoneNumber', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('dateRegistered', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('Guest', 'Guest'), ('Receptionist', 'Receptionist'), ('Hotel Admin', 'Hotel Admin')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
