# Generated by Django 2.0.7 on 2018-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_Of_Adults', models.CharField(max_length=40)),
                ('number_Of_Children', models.CharField(max_length=40)),
            ],
        ),
    ]
