# Generated by Django 2.0.7 on 2018-07-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_Date', models.DateTimeField(auto_now_add=True)),
                ('hotel_image', models.ImageField(upload_to='hotelpicturesimage/')),
            ],
        ),
        migrations.CreateModel(
            name='HotelProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_Address', models.CharField(max_length=200)),
                ('hotel_Pictures', models.ImageField(upload_to='hotelprofileimage/')),
                ('hotel_Logistics', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.HotelProfile')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_Number', models.CharField(max_length=15)),
                ('room_Type', models.CharField(max_length=200)),
                ('room_Bed_Type', models.CharField(max_length=25)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.HotelProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_Date', models.DateTimeField(auto_now_add=True)),
                ('room_image', models.ImageField(upload_to='roompicturesimage/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupationStatus', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], max_length=40)),
                ('starting_Date', models.CharField(max_length=40)),
                ('ending_Date', models.CharField(max_length=40)),
                ('status_UpdateTime', models.CharField(max_length=40)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.Room')),
            ],
        ),
        migrations.AddField(
            model_name='hotelpictures',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.HotelProfile'),
        ),
    ]
