# Generated by Django 2.0.7 on 2018-08-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_hotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_image', models.ImageField(upload_to='hotel_images/')),
                ('hotel_address', models.CharField(max_length=250)),
                ('hotel_contact', models.CharField(max_length=20)),
                ('brief_description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
