# Generated by Django 2.0.7 on 2018-09-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_auto_20180831_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(choices=[('lagos', 'LAGOS'), ('abuja', 'Abuja'), ('owerri', 'OWERRI'), ('port-harcourt', 'PORT-HARCOURT'), ('delta', 'DELTA'), ('calabar', 'CALABAR'), ('uyo', 'UYO'), ('enugu', 'ENUGU'), ('owerri', 'OWERRI'), ('kano', 'KANO')], default='lagos', max_length=15),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
    ]
