# Generated by Django 2.0.7 on 2018-09-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_auto_20180904_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(choices=[('lagos', 'LAGOS'), ('abuja', 'Abuja'), ('owerri', 'OWERRI'), ('portharcourt', 'PORTHARCOURT'), ('delta', 'DELTA'), ('calabar', 'CALABAR'), ('uyo', 'UYO'), ('enugu', 'ENUGU'), ('owerri', 'OWERRI'), ('kano', 'KANO')], default='lagos', max_length=15),
        ),
    ]
