# Generated by Django 2.0.7 on 2018-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_auto_20180904_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image',
            field=models.FileField(upload_to='hotel_images/'),
        ),
        migrations.AlterField(
            model_name='hotelpictures',
            name='hotel_image',
            field=models.FileField(upload_to='hotelpicturesimage/'),
        ),
        migrations.AlterField(
            model_name='hotelprofile',
            name='hotel_Pictures',
            field=models.FileField(upload_to='hotelprofileimage/'),
        ),
    ]
