# Generated by Django 2.0.7 on 2018-09-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_auto_20180918_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='brief_description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_contact',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='hotelprofile',
            name='hotel_Address',
        ),
        migrations.RemoveField(
            model_name='hotelprofile',
            name='hotel_Logistics',
        ),
        migrations.RemoveField(
            model_name='hotelprofile',
            name='hotel_Pictures',
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='brief_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='hotel_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='hotel_contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
