# Generated by Django 2.0.7 on 2018-09-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_auto_20180920_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='location',
            field=models.CharField(choices=[('lagos', 'LAGOS'), ('abuja', 'Abuja'), ('owerri', 'OWERRI'), ('portharcourt', 'PORTHARCOURT'), ('delta', 'DELTA'), ('calabar', 'CALABAR'), ('uyo', 'UYO'), ('enugu', 'ENUGU'), ('owerri', 'OWERRI'), ('kano', 'KANO')], default='select state', max_length=50),
        ),
    ]
