# Generated by Django 2.0.7 on 2018-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0009_hotelprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpictures',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
