# Generated by Django 2.0.7 on 2018-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0010_hotelpictures_image_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AlterField(
            model_name='hotelpictures',
            name='hotel_image',
            field=models.FileField(upload_to='Hotel/Hotel/Pictures/'),
        ),
        migrations.AlterField(
            model_name='roompictures',
            name='room_image',
            field=models.FileField(upload_to='Hotel/Room/Pictures/'),
        ),
    ]
