# Generated by Django 2.0.7 on 2018-10-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0011_auto_20181002_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_Number',
        ),
        migrations.AddField(
            model_name='room',
            name='room_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotelpictures',
            name='hotel_image',
            field=models.FileField(null=True, upload_to='Hotel/Hotel/Pictures/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_Type',
            field=models.CharField(max_length=15),
        ),
    ]
