# Generated by Django 2.0.7 on 2018-10-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0012_auto_20181003_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
