# Generated by Django 2.0.7 on 2018-10-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0013_room_room_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_Bed_Type',
            new_name='room_bed_type',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_Type',
            new_name='room_type',
        ),
    ]
