# Generated by Django 2.0.7 on 2018-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0014_auto_20181004_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='hotel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_image_name',
        ),
        migrations.AddField(
            model_name='roompictures',
            name='room_image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
