# Generated by Django 2.0.7 on 2018-10-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0015_auto_20181004_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_descriptions', models.CharField(max_length=300)),
                ('category_attributes', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel.RoomCategories'),
        ),
    ]
