# Generated by Django 2.0.7 on 2018-10-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0016_auto_20181004_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategories',
            name='category_attributes',
        ),
        migrations.AlterField(
            model_name='roomcategories',
            name='category_name',
            field=models.TextField(max_length=50),
        ),
    ]
