# Generated by Django 2.0.7 on 2018-10-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0017_auto_20181005_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(max_length=50)),
                ('category_descriptions', models.CharField(max_length=300)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.HotelProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_category',
        ),
        migrations.DeleteModel(
            name='RoomCategories',
        ),
    ]
