# Generated by Django 2.0.7 on 2018-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0019_auto_20181010_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='category_descriptions',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
