# Generated by Django 2.0.7 on 2018-10-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0020_auto_20181010_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='category_descriptions',
            field=models.TextField(),
        ),
    ]
