# Generated by Django 2.0.7 on 2018-10-18 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0024_auto_20181011_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roompictures',
            name='room',
        ),
        migrations.AddField(
            model_name='roompictures',
            name='roomcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel.RoomCategory'),
        ),
    ]
