# Generated by Django 2.0.7 on 2018-10-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0025_auto_20181018_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel.HotelProfile'),
        ),
    ]
