# Generated by Django 2.0.7 on 2018-10-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0026_roomcategory_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_rate',
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='room_rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
