# Generated by Django 2.0.7 on 2018-11-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0028_auto_20181030_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstatus',
            name='ending_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='starting_Date',
            field=models.DateTimeField(),
        ),
    ]
