# Generated by Django 2.0.7 on 2018-11-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Hotel', '0028_auto_20181030_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_In_Date', models.CharField(max_length=40)),
                ('check_Out_Date', models.CharField(max_length=40)),
                ('how_many_guests', models.CharField(blank=True, max_length=10, null=True)),
                ('additional_request', models.CharField(blank=True, max_length=100, null=True)),
                ('reservation_Date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('CreditCard', 'CreditCard'), ('Cash', 'Cash')], max_length=20)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.UserInfo')),
                ('reserved_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.RoomStatus')),
            ],
        ),
    ]
